[package]
name = "system-stats-api"
version = "0.1.0"
authors = ["Steven Goldberg"]
edition = "2018"

[dependencies]
systemstat = "0.1.7"
#sysinfo = "0.16"
#tokio = { version = "1.2", features = ["full"] }
#tokio-stream = "0.1"
#heim = "0.0.11"